services:
   # Services
   brille24_tier_price.services.product_variant_price_calculator:
       class: Brille24\SyliusTierPricePlugin\Services\ProductVariantPriceCalculator
       arguments: ['@sylius.calculator.product_variant_price', '@brille24_tier_price.services.tier_price_finder']

   brille24_tier_price.services.tier_price_finder:
       class: Brille24\SyliusTierPricePlugin\Services\TierPriceFinder
       arguments: ['@brille24.repository.tierprice']

#    sylius.order_processing.order_prices_recalculator:
#        class: Brille24\SyliusTierPricePlugin\Services\OrderPricesRecalculator
#        arguments: ['@brille24_tier_price.services.product_variant_price_calculator']
#        tags:
#            - {name: sylius.order_processor, priority: 40}
