services:
    brille24_tier_price.fixtures.product_variant_fixture:
        class: Brille24\SyliusTierPricePlugin\Fixtures\TierPriceFixture
        arguments: ['@doctrine.orm.default_entity_manager', '@brille24_tierprice_tierprice_factory']
        tags:
            - { name: sylius_fixtures.fixture }
