services:
    # Sonata
    brille24_tier_price.block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@Brille24SyliusTierPricePlugin/Resources/views/Admin/_javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }

    brille24_tier_price.block_event_listener.shop.layout.javascripts.tierprice:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@Brille24SyliusTierPricePlugin/Resources/views/Shop/_javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

    brille24_tier_price.sylius.admin.product.update.tab_details:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@Brille24SyliusTierPricePlugin/Resources/views/Admin/Product/ProductVariant/_product_variants.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.product.update.tab_details, method: onBlockEvent }

    brille24_tier_price.sylius.product.show_before_add_to_cart:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@Brille24SyliusTierPricePlugin/Resources/views/Shop/Product/Show/_tier_price_promo.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.before_add_to_cart, method: onBlockEvent }
