# Overriding product variant of sylius
sylius_product:
    resources:
        product_variant:
            classes:
                model: Brille24\TierPriceBundle\Entity\ProductVariant

# New resources
sylius_resource:
  resources:
    brille24.tierprice:
      classes:
        model: Brille24\TierPriceBundle\Entity\TierPrice
        form: Brille24\TierPriceBundle\Form\TierPriceType
        repository: Brille24\TierPriceBundle\Repository\TierPriceRepository