services:
    # Form types
    brille24_tier_price.form.tier_price_type:
        class: Brille24\TierPriceBundle\Form\TierPriceType
        arguments: ['@sylius.repository.channel']
        tags:
            - {'name': form.type}

    #Form type Extensions
    brille24_tier_price.form.extension.product_variant_type:
        class: Brille24\TierPriceBundle\Form\Extension\ProductVariantTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType }

    #Event listener
    app.listener.admin.product_variant.form.menu_builder:
        class: Brille24\TierPriceBundle\Menu\AdminProductVariantFormMenuListener
        arguments: ['@sylius.theme.translation.theme_aware_translator.inner']
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.product_variant.form, method: addItems }

    # Sonata
    block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@Brille24TierPriceBundle/Resources/views/Admin/_javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }

    brille24_tier_price.sylius.admin.product.update.tab_details:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@Brille24TierPriceBundle/Resources/views/Admin/Product/ProductVariant/_product_variants.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.product.update.tab_details, method: onBlockEvent }

    brille24_tier_price.sylius.product.show_before_add_to_cart:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@Brille24TierPriceBundle/Resources/views/Shop/Product/Show/_tier_price_promo.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.before_add_to_cart, method: onBlockEvent }

    # Services
    brille24_tier_price.services.product_variant_price_calculator:
        class: Brille24\TierPriceBundle\Services\ProductVariantPriceCalculator
        arguments: ['@sylius.calculator.product_variant_price', '@brille24_tier_price.services.tier_price_finder']

    brille24_tier_price.services.tier_price_finder:
        class: Brille24\TierPriceBundle\Services\TierPriceFinder
        arguments: ['@brille24_tier_price.repository.tier_price_repository']

#    sylius.order_processing.order_prices_recalculator:
#        class: Brille24\TierPriceBundle\Services\OrderPricesRecalculator
#        arguments: ['@brille24_tier_price.services.product_variant_price_calculator']
#        tags:
#            - {name: sylius.order_processor, priority: 40}

imports:
  - {resources: "services/repositories.xml"}